// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmZGmV3a19ZpWh0aBpK5pG2pTcmJM8oy0',
    appId: '1:784069472391:web:4819dab5037924193c0822',
    messagingSenderId: '784069472391',
    projectId: 'havelsan-map',
    authDomain: 'havelsan-map.firebaseapp.com',
    storageBucket: 'havelsan-map.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsFzZzQtky6FBZ0bWMgm7aUAGA6zxwXTg',
    appId: '1:784069472391:android:a58bac198ae922333c0822',
    messagingSenderId: '784069472391',
    projectId: 'havelsan-map',
    storageBucket: 'havelsan-map.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvJQ_gbLwydtQHor3kfShZ2p7vUwXUT0s',
    appId: '1:784069472391:ios:44d02e0ee8b067e73c0822',
    messagingSenderId: '784069472391',
    projectId: 'havelsan-map',
    storageBucket: 'havelsan-map.appspot.com',
    iosClientId: '784069472391-18mdm9a9vm3soe4sditr79585r94lonb.apps.googleusercontent.com',
    iosBundleId: 'com.example.googleMao',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvJQ_gbLwydtQHor3kfShZ2p7vUwXUT0s',
    appId: '1:784069472391:ios:44d02e0ee8b067e73c0822',
    messagingSenderId: '784069472391',
    projectId: 'havelsan-map',
    storageBucket: 'havelsan-map.appspot.com',
    iosClientId: '784069472391-18mdm9a9vm3soe4sditr79585r94lonb.apps.googleusercontent.com',
    iosBundleId: 'com.example.googleMao',
  );
}
